Update pact_broker.yml

diff --git a/.github/workflows/pact_broker.yml b/.github/workflows/pact_broker.yml
--- a/.github/workflows/pact_broker.yml
+++ b/.github/workflows/pact_broker.yml
@@ -24,17 +24,22 @@ jobs:
       - name: Start Services with Docker Compose
         run: docker compose up -d
 
+      - name: List Running Docker Containers
+        run: docker ps -a
+
       - name: Wait for Services to Start
-        run: sleep 15
+        run: sleep 30
 
       - name: Verify Pact Broker is Running
         run: curl -f http://localhost:9292 || (echo "Pact Broker failed to start" && exit 1)
 
       - name: Verify Consumer Service is Running
-        run: curl -f http://localhost:3000 || (echo "Consumer service failed to start" && exit 1)
+        run: |
+          curl -f http://localhost:3000 || (echo "Consumer service failed to start" && docker logs consumer-service && exit 1)
 
       - name: Verify Provider Service is Running
-        run: curl -f http://localhost:4000 || (echo "Provider service failed to start" && exit 1)
+        run: |
+          curl -f http://localhost:4000 || (echo "Provider service failed to start" && docker logs provider-service && exit 1)
 
       - name: Run Consumer Pact Tests
         run: docker exec consumer-service npm test
